<a href="https://colab.research.google.com/github/tarunchittora/GRIP-the-sparks-foundation/blob/main/regression_case_study_with_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
dataset=pd.read_excel("Folds5x2_pp.xlsx")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [7]:
ann = tf.keras.models.Sequential()

In [8]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))

In [9]:
ann.compile(optimizer="adam",loss="mean_squared_error")

In [10]:
ann.fit(X_train,y_train,batch_size=32,epochs=100 )

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 53898.6680
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 390.3973
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 354.9196
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 314.5833
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 272.6021
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 232.0410
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 194.2329
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 159.7309
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 130.7686
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 107.0350
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 88.7609
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - los

In [13]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))



[[427.34 431.23]
 [458.3  460.01]
 [461.77 461.14]
 ...
 [469.03 473.26]
 [435.94 438.  ]
 [455.11 463.28]]
